### ISSUE TITLE
I'm not seeing the pull requests, so I can't give you :beers:

### ISSUE THREAD

**Issue by suweller** [Hetty82/demo_app#1]
:beers: for finishing the app, now use pull requests in order for me to more easily give :beers:, or feedback ;-)

**Comment by Hetty82** [comment]
ja vanaf nu wordt het echt. met branches enzo. pr's coming up.

**Comment by Hetty82** [comment]
de code is wel nogal voorgeschreven. maar feedback kan nog steeds wel nuttig zijn. (nieuwere, betere oplossingen enzo).

tnx :smile:

**Comment by suweller** [comment]
:+1: :-)
